version: '3.8'

services:
  defaceit:
    build: .
    image: defaceit:latest
    container_name: defaceit-app
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./input:/app/input
      - ./output:/app/output
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
    network_mode: host
    stdin_open: true
    tty: true

